/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface _CfMETADATA {
  key: Generated<number | null>;
  value: Buffer | null;
}

export interface ApiTokens {
  created_at: Generated<number>;
  expires_at: number | null;
  id: string;
  name: string;
  token_hash: string;
  user_id: string;
}

export interface D1Migrations {
  applied_at: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface Devices {
  created_at: Generated<number>;
  endpoint: string;
  id: string;
  last_seen_at: Generated<number>;
  name: string;
  subscription: string;
  user_id: string;
}

export interface DeviceTopics {
  device_id: string;
  topic: string;
}

export interface InvitationCodes {
  code: string;
  created_at: Generated<number>;
  created_by: string;
  status: Generated<string>;
  used_at: number | null;
  used_by: string | null;
}

export interface Users {
  created_at: Generated<number>;
  id: string;
  password_hash: string;
  role: string;
  username: string;
}

export interface UserTopics {
  created_at: Generated<number>;
  name: string;
  user_id: string;
}

export interface DB {
  _cf_METADATA: _CfMETADATA;
  api_tokens: ApiTokens;
  d1_migrations: D1Migrations;
  device_topics: DeviceTopics;
  devices: Devices;
  invitation_codes: InvitationCodes;
  user_topics: UserTopics;
  users: Users;
}
